// import Home from './pages/Home'
import Appoitment from './features/Appoitment'
import Doctors from './features/Doctors'
import Patients from './features/Patients'
import Button from './components/Button'
import Input from './components/Input'
import CardForPatient from './components/CardForPatient'
import CardForDoctor from './components/CardForDoctor'
import Navbar from './components/Navbar'

import PatientContextProvider from './context/Patient/PateintContextProvider'
import AppointmentContextProvider from './context/Appointment/AppointmentContextProvider'
import DoctorContextProvider from './context/Doctor/DoctorContextProvider'
import PatientContext from './context/Patient/PateintContext'
import AppointmentContext from './context/Appointment/AppointmentContext'
import DoctorContext from './context/Doctor/DoctorContext'
import Model from './components/Model'
import Home from './pages/Home'
import Login from './pages/Login'
import Dashbord from './pages/Dashbord'
import {addPatientAPI,deletePatientAPI,getPatientsAPI,updatePatientAPI} from './services/patientService'
import {addDoctorAPI,deleteDoctorAPI,getDoctorsAPI,updateDoctorAPI} from './services/DoctorService'
import {addAppointmentAPI,deleteAppointmentAPI,getAppointmentsAPI,updateAppointmentAPI} from './services/appoinmentService'
import PatientForm from './components/PatientForm'
import ModelForPatient from './components/ModelForPatient'
import ModelForDoctor from './components/ModelForDoctor'
import UpdateFormForPatient from './components/UpdateFormForPatient'
import UpdateFormForDoctor from './components/UpdateFormForDoctor'
import DoctorForm from './components/DoctorForm'
import RescheduleModel from './components/RescheduleModel'
import CardForAppointment from './components/CardForAppointment'
import useModal from './hooks/useModel'
import useForm from './hooks/useForm'

export { Appoitment, Doctors, Patients, Button, Input, CardForPatient, CardForDoctor, Navbar, PatientContextProvider, AppointmentContextProvider, DoctorContextProvider, Model,Home,Login,Dashbord,PatientContext,AppointmentContext,DoctorContext ,addPatientAPI,deletePatientAPI,getPatientsAPI,updatePatientAPI,addDoctorAPI,deleteDoctorAPI,updateDoctorAPI,getDoctorsAPI,addAppointmentAPI,updateAppointmentAPI,deleteAppointmentAPI,getAppointmentsAPI,PatientForm,ModelForPatient,ModelForDoctor,UpdateFormForPatient,DoctorForm,UpdateFormForDoctor,CardForAppointment,RescheduleModel,useModal,useForm}